"use client"
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserContext } from "@/src/contexts/UserContext";
import { useEffect, useState } from "react";
import { Empresa, Usuario } from "@/src/types/types";
import { EmpresaContext } from "@/src/contexts/EmpresaContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

 const [user,setUser]= useState<Usuario | null>(null)
 const [empresa,setEmpresa]= useState<Empresa | null>(null)
 useEffect(()=>{
  const localStorageUser = localStorage.getItem("user")
  
  if(!localStorageUser){
    return
  }
  const User = JSON.parse(localStorageUser!)
  setUser(User)
 },[ ])
//  console.log(user);
 
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
            <UserContext.Provider  value={{user,setUser}}>
              <EmpresaContext.Provider value={{empresa,setEmpresa}}>
                <main>
                  {children}
                </main>
              </EmpresaContext.Provider>
            </UserContext.Provider>
   
      </body>
    </html>
  );
}
